title: 'TTS {{System}} Status'
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://cstate.mnts.lt'
params:
  alwaysKeepBrandColor: true
  brand: '#112e51'
  categories:
    - name: Website
      description: Website(s) are located here.
    - name: API
      description: API(s) are located here.
    - name: Database
      description: Database(s)are located here.
    - name: Network
      description: Networking component(s) are located here.   
  dateFormat: 'Monday, January 2, 2006 15:04 MST'
  description: |
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disableDarkMode: false
  disrupted: '#e98e1e'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: all
  incidentPostsPerPage: 10
  logo: /img/favicon.png
  notice: '#4349fb'
  ok: '#2fcc66'
  shortDateFormat: 'Monday, January 2, 2006 15:04 MST'
  systems:
    - name: CMS
      description: Frontend of the system.
      category: Website
    - name: Swagger
      description: The guts of the application.
      category: API
    - name: Postgresql
      description: The guts of the application.
      category: Database
    - name: Redis
      description: The guts of the application.
      category: Database         
    - name: Cloudfront
      description: |
        This is the service responsible for serving images, audio, and video. It
        is reliant on our CDN.
      category: Network
  useLargeHeaderDesign: false
  useLogo: true
#theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
