title: 'TTS {{System}} Status'
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://cstate.mnts.lt'
params:
  alwaysKeepBrandColor: true
  brand: '#112e51'
  categories:
    - closed: true
      description: The main servers are located here.
      name: North Coast
    - name: East Coast
    - name: Uncategorized
  dateFormat: 'Monday, January 2, 2006 15:04 MST'
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disableDarkMode: true
  disrupted: '#e98e1e'
  down: '#e60000'
  googleAnalytics: UA-00000000-1
  incidentHistoryFormat: yearly
  incidentPostsPerPage: 10
  logo: /img/favicon.png
  notice: '#4349fb'
  ok: '#2fcc66'
  shortDateFormat: 'Monday, January 2, 2006 15:04 MST'
  systems:
    - category: North Coast
      name: Gateway
    - category: East Coast
      name: Backup Gateway
    - category: Uncategorized
      description: The guts of the application.
      name: API
    - category: Uncategorized
      description: >-
        This is the service responsible for serving images, audio, and video. It
        is reliant on our CDN.
      name: Media Proxy
  useLargeHeaderDesign: false
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  home:
    - html
    - json
    - rss
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
